services:
  node:
    env_file:
      - selected.env
    image: node:lts-hydrogen
    command: sh -c "npx yarn install && npm start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - selected
  mongo:
    env_file:
      - selected.env
    image: mongo:focal
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
    networks:
      - selected
networks:
  selected:
