import { PassportStrategy } from '@nestjs/passport';
import { Strategy, VerifyCallback } from 'passport-google-oauth20';
import { Injectable } from '@nestjs/common';
import { ENVConstants } from 'src/env.constants';
import { JwtService } from '@nestjs/jwt';
import { InjectModel } from '@nestjs/mongoose';
import { User, UserDocument } from 'src/user/user.schema';
import { Model } from 'mongoose';

@Injectable()
export class GoogleStrategy extends PassportStrategy(Strategy) {
  /**
   * The constructor function is called when a new instance of the class is created
   */
  constructor(
    private readonly jwtService: JwtService,
    @InjectModel(User.name) private userModel: Model<UserDocument>,
  ) {
    super({
      clientID: ENVConstants.ClientId,
      clientSecret: ENVConstants.ClientSecret,
      callbackURL: 'http://localhost:3000/auth/redirect',
      scope: ['email', 'profile'],
    });
  }

  /**
   * It takes the user's profile information from Google, creates a user object, and passes it to the
   * done callback
   * @param {string} accessToken - The access token that was generated by Google.
   * @param {string} refreshToken - The refresh token is only returned if the offline_access scope is
   * requested.
   * @param {any} profile - This is the user's profile information from Google.
   * @param {VerifyCallback} done - This is a callback function that is called when the authentication is
   * complete.
   */
  async validate(
    accessToken: string,
    refreshToken: string,
    profile: any,
    done: VerifyCallback,
  ): Promise<any> {
    const { name, emails, photos } = profile;
    const user = {
      email: emails[0].value,
      firstName: name.givenName,
      lastName: name.familyName,
      picture: photos[0].value,
      jwt: '',
    };
    const { email, firstName, lastName, picture } = user;
    const result = await this.userModel.findOne({ email: email });
    if (!result) {
      const newUser = new this.userModel({
        email,
        firstName,
        lastName,
        picture,
      });
      newUser.save();
    }
    const payload = { email, firstName, lastName, picture };
    const jwt = this.jwtService.sign(payload);
    user.jwt = jwt;
    done(null, user);
  }
}
